package com.tdis.common.enums;

public enum AsignaturaFormacion {
    DESARROLLO_HUMANO_Y_VALORES,
    HABILIDADES_SOCIOEMOCIONALES,
    DESARROLLO_DEL_PENSAMIENTO_CRITICO,
    ETICA_Y_VALORES,
    LIDERAZGO_DE_EQUIPOS_DE_ALTO_DESEMPENO,
    HABILIDADES_GERENCIALES
}